




// Category Definition
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const GET_ERROR = "GET_ERROR"
export const CREATE_CATEGORY = "CREATE_CATEGORY"

export const ALL_CATEGORIES = "ALL_CATEGORIES"
export const REMOVE_CATEGORY = "REMOVE_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"
export const GET_SPECIFIC_CATEGORY = "GET_SPECIFIC_CATEGORY"

// brand Definition
export const GET_ALL_BRAND = "GET_ALL_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"

export const ALL_BRANDS = "ALL_BRANDS"
export const REMOVE_BRAND = "REMOVE_BRAND"
export const EDIT_BRAND = "EDIT_BRAND"
export const GET_SPECIFIC_BRAND = "GET_SPECIFIC_BRAND"

// subCategory Definition
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"
export const GET_SUB_CATEGORY_BY_MAIN_CATEGORY_ID = "GET_SUB_CATEGORY_BY_MAIN_CATEGORY_ID"

export const ALL_SUB_CATEGORIES = "ALL_SUB_CATEGORIES"
export const REMOVE_SUB_CATEGORY = "REMOVE_SUB_CATEGORY"
export const EDIT_SUB_CATEGORY = "EDIT_SUB_CATEGORY"
export const GET_SPECIFIC_SUB_CATEGORY = "GET_SPECIFIC_SUB_CATEGORY"

// product Definition
export const GET_HOME_PRODUCT = "GET_HOME_PRODUCT"
export const MOST_SALES_PRODUCTS = "MOST_SALES_PRODUCTS"
export const MARKET_PRODUCTS = "MARKET_PRODUCTS"
export const HOME_DEVICES_PRODUCTS = "HOME_DEVICES_PRODUCTS"
export const SAMSUNG_PRODUCTS = "SAMSUNG_PRODUCTS"
export const GET_PAGE_PRODUCT = "GET_PAGE_PRODUCT"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_SPECIFIC_PRODUCT = "GET_SPECIFIC_PRODUCT"
export const GET_CATEGORY_NAME_DEPEND_ON_ID = "GET_CATEGORY_NAME_DEPEND_ON_ID"
export const GET_BRAND_NAME_DEPEND_ON_ID = "GET_BRAND_NAME_DEPEND_ON_ID"
export const GET_ALL_PRODUCTS_BY_CATEGORY_ID = "GET_ALL_PRODUCTS_BY_CATEGORY_ID"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const SEARCH_PRODUCT = "SEARCH_PRODUCT"

// Authentication Definition
export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
// export const LOGOUT_USER = "LOGOUT_USER"
export const FORGET_PASSWOR_EMAIL = "FORGET_PASSWOR_EMAIL"
export const FORGET_PASSWOR_CODE = "FORGET_PASSWOR_CODE"
export const FORGET_PASSWOR_NEW_PASSWORD = "FORGET_PASSWOR_NEW_PASSWORD"
export const LOGGED_USER_DATA = "LOGGED_USER_DATA"

// review Definition
export const ADD_REVIEW = "ADD_REVIEW"
export const ALL_REVIEWS = "ALL_REVIEWS"
export const ALL_REVIEW_2 = "ALL_REVIEW_2"
export const REMOVE_REVIEW = "REMOVE_REVIEW"
export const EDIT_REVIEW = "EDIT_REVIEW"
export const GET_SPECIFIC_REVIEW = "GET_SPECIFIC_REVIEW"

// wishList Definition
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const GET_ALL_WISHLIST = "GET_ALL_WISHLIST"
export const REMOVE_WISHLIST = "REMOVE_WISHLIST"

// coupons Definition
export const ADD_COUPON = "ADD_COUPON"
export const GET_ALL_COUPONS = "GET_ALL_COUPONS"
export const GET_SPECIFIC_COUPON = "GET_SPECIFIC_COUPON"
export const UPDATE_COUPON = "UPDATE_COUPON"
export const REMOVE_COUPON = "REMOVE_COUPON"

// address Definition
export const ADD_ADDRESS = "ADD_ADDRESS"
export const GET_ALL_ADDRESSES = "GET_ALL_ADDRESSES"
export const GET_SPECIFIC_ADDRESS = "GET_SPECIFIC_ADDRESS"
export const GET_SPECIFIC_ADDRESS_FIX = "GET_SPECIFIC_ADDRESS_FIX"
export const UPDATE_ADDRESS = "UPDATE_ADDRESS"
export const REMOVE_ADDRESS = "REMOVE_ADDRESS"

// user Definition
export const GET_USER_DATA = "GET_USER_DATA"
export const UPDATE_USER_DATA = "UPDATE_USER_DATA"
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"

// cart Definition
export const ADD_TO_CART = "ADD_TO_CART"
export const ALL_CARTS = "ALL_CARTS"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const EDIT_CART_ITEM_QUANTITY = "EDIT_CART_ITEM_QUANTITY"
export const CLEAR_ALL_CART = "CLEAR_ALL_CART"
export const APPLY_COUPON = "APPLY_COUPON"

// payment Definition
export const CREATE_CASH_ORDER = "CREATE_CASH_ORDER"
export const GET_ALL_ORDERS = "GET_ALL_ORDERS"
export const GET_SPECIFIC_ORDER = "GET_SPECIFIC_ORDER"
export const PAID_UPDATE = "PAID_UPDATE"
export const DELIVER_UPDATE = "DELIVER_UPDATE"
export const CHECKOUT_SESSION = "CHECKOUT_SESSION"
export const ADD_UPDATE = "ADD_UPDATE"
export const DELETE_UPDATE = "DELETE_UPDATE"

// adminUsers Definition
export const GET_ALL_USERS = "GET_ALL_USERS"
export const CHANGE_TO_ADMIN = "CHANGE_TO_ADMIN"
export const CHANGE_TO_USER = "CHANGE_TO_USER"
export const DEACTIVATE_ACOUNT = "DEACTIVATE_ACOUNT"
export const ACTIVATE_ACCOUNT = "ACTIVATE_ACCOUNT"

// fees Definition
export const GET_ALL_FEES = "GET_ALL_FEES"
export const GET_SPECIFIC_FEES = "GET_SPECIFIC_FEES"
export const UPDATE_FEES = "UPDATE_FEES"
export const CREATE_FEES = "CREATE_FEES"

// carousel Definition
export const GET_ALL_CAROUSEL = "GET_ALL_CAROUSEL"
export const CREATE_CAROUSEL = "CREATE_CAROUSEL"
export const GET_SPECIFIC_CAROUSEL = "GET_SPECIFIC_CAROUSEL"
export const UPDATE_CAROUSEL = "UPDATE_CAROUSEL"
export const DELETE_CAROUSEL = "DELETE_CAROUSEL"

// email Definition
export const SEND_EMAIL_TO_USER = "SEND_EMAIL_TO_USER"
export const SEND_EMAIL_TO_ME = "SEND_EMAIL_TO_ME"

// logged user Definition
export const LOGGED_USER_DATA_2 = "LOGGED_USER_DATA_2"

// link dispatch and selector
export const ANY_DATA = "ANY_DATA"